### ISSUE TITLE
You think this is a game?

### ISSUE THREAD

**Issue by thaibeouu** [phanan/tieqviet#5]
`Đúng thế anh ạ. Cảm ơn anh. Ngày mới vui vẻ.`
`https://www.youtube.com/watch?v=tUAYBteh5zk`

**Comment by paladin3895** [comment]
Github là nơi trao đổi và review code, ko phải mạng xã hội. Xin đừng tạo issue ko liên quan đến project. Bất kì nhà tuyển dụng nào khi nhìn vào lịch sử tương tác của bạn sẽ ko đánh giá bạn cao đâu.

**Comment by thaibeouu** [comment]
Hmm hiển nhiên cái issue này là spam, nhưng trong một side-project với tinh thần trào lộng vui vẻ thì ta bày tỏ thiện chí một chút liệu có quá đáng trách? Không rõ quan điểm của anh An thế nào?

**Comment by phanan** [comment]
Anh không có ý kiến :D
