### ISSUE TITLE
How about conversion from Tiếq Việt to Tiếng Việt?

### ISSUE THREAD

**Issue by kimkha** [phanan/tieqviet#6]
I'm sure we should have a dictionary to convert like that... But it's really helpful!

**Comment by thaibeouu** [comment]
Obviously can't, e.g. d/gi/r lead to z and there's no way to find the respective original consonant.

**Comment by kimkha** [comment]
I know, that's why I think you should have a dictionary, which combine two or more to guest the word.

**Comment by tuanluu-agilityio** [comment]
Duplicate on issue #2

**Comment by phanan** [comment]
Yup. Reverse-engineering isn't that simple. Machine learning might need to be involved even.
